### 测试服务器登陆接口
POST http://122.9.36.233:8080/api/login
Content-Type: application/json

{
  "number": "1006",
  "password": "1006"
}


### 测试登陆接口
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "1001",
  "password": "1001"
}
### 测试登陆接口
POST http://localhost:8080/api/login
Content-Type: application/json

{
"number": "string2",
"password": "string2"
}


### 测试请求地址出错
POST http://localhost:8080/api/loginCount
Content-Type: application/json

{
  "number": "2018214444",
  "password": "2018214444"
}

### 测试参数类型不匹配
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": 2018214444,
  "password": "2018214444"
}

### 测试参数不合法
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "2018214444",
  "passwords": "2018214444"
}

###


