### 获取所有教师
GET http://122.9.36.233:8080/api/sadmin/teachers
authorization: a7b799e87429ef6b8c44e2856ffc482f71764e8395f0f407edc3f1b076099e07e5e36996ed2cd2dcb30e798c1f0304f6e5333bcbe11f727cc164151c966723af
Content-Type: application/json

### 导入教师名单
POST http://localhost:8080/api/sadmin/teachers
authorization: a7b799e87429ef6b8c44e2856ffc482f71764e8395f0f407edc3f1b076099e07e5e36996ed2cd2dcb30e798c1f0304f6e5333bcbe11f727cc164151c966723af
Content-Type: application/json

[
  {
    "number": "1003",
    "name": "李明",
    "role": "2",
    "title": "讲师"
  },
  {
    "number": "1004",
    "name": "李1",
    "role": "2",
    "title": "讲师"
  },
  {
    "number": "1005",
    "name": "李2",
    "role": "4",
    "title": "讲师"
  },
  {
    "number": "1006",
    "name": "李6",
    "role": "2",
    "title": "讲师"
  },
  {
    "number": "1007",
    "name": "李7",
    "role": "4",
    "title": "讲师"
  },
  {
    "number": "1008",
    "name": "李8",
    "role": "2",
    "title": "讲师"
  },
  {
    "number": "1009",
    "name": "李9",
    "role": "2",
    "title": "讲师"
  },
  {
    "number": "1010",
    "name": "李10",
    "role": "2",
    "title": "讲师"
  }
]

###