# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# 工作流名称
name: Java CI with Maven

# 监听
on:
  # 执行操作
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
        # 发布镜像
      - name: push to package
        run: |
          ${{ secrets.DOCKER_LOGIN }}
          docker build . -t docker.pkg.github.com/wenbinai/graduation-process-management/graduation-process-management:latest
          docker push docker.pkg.github.com/wenbinai/graduation-process-management/graduation-process-management:latest
#  # 持续部署
#  deploy:
#    # 需要build执行完才能执行部署
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: deploy
#        # 使用第三方提供的登录actions
#        uses: appleboy/ssh-action@master
#        # 登录需要的参数
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          # 登录后执行命令
#          script: |
#            # 进入到项目文件夹中
#            cd /home/erjiangao/services/tutor-selection-tool
#            # 重新基于docker-compose.yml拉取镜像
#            docker-compose pull
#            # 如果文件名不叫docker-compose.yml，则加-f参数，基于指定文件执行后台启动
#            docker-compose up -d
#            [ $(docker images -f dangling=true docker.pkg.github.com/erjiangao/tutor-selection-tool/tutor-selection-tool:latest -q) ] && \
#            docker rmi $(docker images -f dangling=true docker.pkg.github.com/erjiangao/tutor-selection-tool/tutor-selection-tool:latest -q)
